MyLoveAgency/Controllers/MainController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using MyLoveAgency.Models;
using MyLoveAgency.Models.Database;
using System.Security.Claims;
using System.IO;
using System.Security.Cryptography;
using System.Security.AccessControl;
using System.Text.RegularExpressions;
using System.Net.Mail;
using Microsoft.Identity.Client.Extensions.Msal;
using static Org.BouncyCastle.Crypto.Engines.SM2Engine;
using System.Text;
using Microsoft.AspNetCore.Identity;

namespace MyLoveAgency.Controllers
{
    public class MainController : Controller
    {
        public IActionResult Home()
        {
            // Проверяем валидность cookie "Language"
            if (Request.Cookies["Language"] != "en" && Request.Cookies["Language"] != "ua")
                return Redirect("~/Main/ChangeLanguage?refererPage=Home");

            ViewBag.NamePage = "Home";
            return View();
        }

        [HttpGet]
        [Route("/Main/Services/{nameType?}")]
        public IActionResult Services(string nameType = "")
        {
            // Проверяем валидность cookie "Language"
            if (Request.Cookies["Language"] != "en" && Request.Cookies["Language"] != "ua")
                return Redirect("~/Main/ChangeLanguage?refererPage=Services");

            if (DataClass.TypeService.Count() <= 0) return Redirect("~/Main/Home/");

            if (DataClass.TypeService.Where(x => x.NameEn == nameType).Count() == 1) ViewBag.SelectedType = nameType;
            else ViewBag.SelectedType = DataClass.TypeService[0].NameEn;

            ViewBag.NamePage = "Services/" + ViewBag.SelectedType;
            return View();
        }

        public IActionResult Gallery()
        {
            // Проверяем валидность cookie "Language"
            if (Request.Cookies["Language"] != "en" && Request.Cookies["Language"] != "ua")
                return Redirect("~/Main/ChangeLanguage?refererPage=Gallery");

            ViewBag.NamePage = "Gallery";
            return View();
        }

        public IActionResult FAQ()
        {
            // Проверяем валидность cookie "Language"
            if (Request.Cookies["Language"] != "en" && Request.Cookies["Language"] != "ua")
                return Redirect("~/Main/ChangeLanguage?refererPage=FAQ");

            ViewBag.NamePage = "FAQ";
            return View();
        }

        [HttpGet]
        [Route("/Main/Contact/{selectedData?}")]
        public IActionResult Contact(string selectedData = "")
        {
            // Проверяем валидность cookie "Language"
            if (Request.Cookies["Language"] != "en" && Request.Cookies["Language"] != "ua")
                return Redirect("~/Main/ChangeLanguage?refererPage=Contact");

            string[] partData = selectedData.Split("|");
            ViewBag.SelectedData = partData;

            ViewBag.NamePage = "Contact";
            return View();
        }

        public IActionResult ChangeLanguage(string refererPage)
        {
            if (Request.Cookies["Language"] != "en" && Request.Cookies["Language"] != "ua")
            {
                Response.Cookies.Delete("Language");
                CreateCookie("Language", "en", 7);

                return Redirect("~/Main/" + refererPage);
            }
            else
            {
                if (Request.Cookies["Language"] == "en")
                {
                    Response.Cookies.Delete("Language");
                    CreateCookie("Language", "ua", 7);
                }
                else
                {
                    Response.Cookies.Delete("Language");
                    CreateCookie("Language", "en", 7);
                }

                return Redirect("~/Main/" + refererPage);
            }
        }

        public IActionResult AcceptCookies(string refererPage)
        {
            CreateCookie("UseCookies", "true", 7);
            return Redirect("~/Main/" + refererPage);
        }

        public string AcceptCookiesWR()
        {
            try
            {
                CreateCookie("UseCookies", "true", 7);
                return "true";
            }
            catch (Exception e)
            {
                ServiceClass.WriteLog("Что-то пошло не так! Время: " + DateTime.Now + "\r\n" + e + "\r\n");
                return "false";
            }
        }

        [NonAction]
        public void CreateCookie(string key, string value, int expiresDay)
        {
            CookieOptions options = new CookieOptions();
            options.Expires = DateTime.Now.AddDays(expiresDay);
            Response.Cookies.Append(key, value, options);
        }

        public IActionResult Manager(string password)
        {
            if (User?.FindFirst("Access") != null)
            {
                if (User?.FindFirst("Access")?.Value == DataClass.password)
                {
                    ViewBag.NamePage = "Manager";
                    return View();
                }
                else
                {
                    HttpContext.SignOutAsync();
                    return Redirect("~/");
                }
            }
            else
            {
                if (password == DataClass.password)
                {
                    var claims = new List<Claim>() { new Claim("Access", DataClass.password) };
                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);

                    HttpContext.SignInAsync(claimsPrincipal);
                    return Redirect("~/Main/Manager/");
                }
                else
                {
                    HttpContext.SignOutAsync();
                    return Redirect("~/");
                }
            }
        }

        [HttpGet]
        [Route("/Main/Service/{id?}")]
        public IActionResult ServiceDetails(string id)
        {
            // Проверяем валидность cookie "Language"
            if (Request.Cookies["Language"] != "en" && Request.Cookies["Language"] != "ua")
                return Redirect("~/Main/ChangeLanguage?refererPage=Service");

            if (DataClass.Services.Count() <= 0) return Redirect("~/Main/Home/");

            bool result = int.TryParse(id, out int idService);
            if (!result || idService < 1) return Redirect("~/Main/Home/");

            if (DataClass.Services.Where(x => x.Id == idService).Count() == 1) ViewBag.IdService = idService;
            else return Redirect("~/Main/Home/");

            ViewBag.NamePage = "Service/" + ViewBag.IdService;
            return View();
        }

        [HttpPost]
        public async Task<string> AddImageService(IFormFile imageServiceInput, string idService)
        {
            try
            {
                if (User?.FindFirst("Access")?.Value != DataClass.password) return "false";

                if (imageServiceInput != null && imageServiceInput.Length > 0 && idService != null)
                {
                    bool result = int.TryParse(idService, out int id);
                    if (!result) return "false";

                    using (var context = new LovelyLoveDbContext())
                    {
                        Service? service = context.Services.FirstOrDefault(x => x.Id == id);
                        if (service == null) return "false";

                        var listImages = context.StorageImageServices.Where(x => x.IdService == service.Id).OrderBy(x => x.Number);

                        string[] part = imageServiceInput.FileName.Split(".");
                        string extensionFile = part[part.Length - 1];

                        Random ran = new Random();
                        int nameFile = -1;

                        while (nameFile == -1)
                        {
                            int numberRan = ran.Next(100000, 1000000);
                            string futureName = numberRan.ToString() + "." + extensionFile.ToString();

                            if (!System.IO.File.Exists(futureName)) nameFile = numberRan;
                        }

                        string path = nameFile.ToString() + "." + extensionFile;
                        int number = listImages.Count() + 1;

                        bool loaded = false;
                        using (var memoryStream = new MemoryStream())
                        {
                            using (var fileStream = new FileStream("wwwroot/data/services/" + path, FileMode.Create))
                            {
                                await imageServiceInput.CopyToAsync(fileStream);
                                loaded = true;
                            }
                        }

                        if (!loaded) return "false";

                        StorageImageService sis = new StorageImageService()
                        {
                            Path = path,
                            Number = number,
                            IdService = service.Id
                        };

                        context.StorageImageServices.Add(sis);
                        context.SaveChanges();

                        DataClass.ServiceImages = context.StorageImageServices.ToList();

                        return path;
                    }
                }
                else return "false";
            }
            catch (Exception e)
            {
                ServiceClass.WriteLog("Что-то пошло не так! Время: " + DateTime.Now + "\r\n" + e + "\r\n");
                return "false";
            }
        }

        [HttpPost]
        public string DeleteImageService(string idService, string number)
        {
            try
            {
                if (User?.FindFirst("Access")?.Value != DataClass.password) return "false";

                if (idService != null && idService != "" && number != null && number != "")
                {

MyLoveAgency/Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/css/bootstrap.min.css" asp-append-version="true">

<link rel="stylesheet" href="~/css/headerstyle.css" asp-append-version="true">
<link rel="stylesheet" href="~/css/footerstyle.css" asp-append-version="true">
<link rel="stylesheet" href="~/css/homestyle.css" asp-append-version="true">
<link rel="stylesheet" href="~/css/newhomestyle.css" asp-append-version="true">
<link rel="stylesheet" href="~/css/servicesstyle.css" asp-append-version="true">
<link rel="stylesheet" href="~/css/detailsstyle.css" asp-append-version="true">
<link rel="stylesheet" href="~/css/gallerystyle.css" asp-append-version="true">
<link rel="stylesheet" href="~/css/faqstyle.css" asp-append-version="true">
<link rel="stylesheet" href="~/css/contactstyle.css" asp-append-version="true">
<link rel="stylesheet" href="~/css/managerstyle.css" asp-append-version="true">

MyLoveAgency/Views/Shared/FooterPartial.cshtml
@{
    if (Context.Request.Cookies["UseCookies"] != "true")
    {
        <style>
            .footer {
                margin-bottom: 60px;
            }
        </style>
    }
}

<div id="mainFooter" class="col-12 footer">

    <div class="col-4 footer-logo-div">
        <img class="footer-logo" src="/data/new_logo_footer.png" alt="" />
    </div>

    <div class="col-4 footer-social">
        <div class="footer-center-div">
            <div class="">
                <a href="https://www.facebook.com/share/w9q92tYN9bfFR9mW/?mibextid=%22%22" target="_blank"><img class="footer-social-img footer-social-facebook" src="/data/facebook_footer.png" alt="" onmouseover="facebookOver()" onmouseout="facebookOut()" /></a>
            </div>

            <div class="">
                <a href="https://www.instagram.com/lovely.love.agency/" target="_blank"><img class="footer-social-img footer-instagram footer-social-instagram" src="/data/instagram_footer.png" alt="" onmouseover="instagramOver()" onmouseout="instagramOut()" /></a>
            </div>

            <div class="">
                <a href="https://t.me/valery_moshchenskaya" target="_blank"><img class="footer-social-img footer-social-telegram" src="/data/telegram_footer.png" alt="" onmouseover="telegramOver()" onmouseout="telegramOut()" /></a>
            </div>
        </div>

        <div>
            <p class="p-copy">Copyrights ©️ 2024 Rock & Roses</p>
        </div>

    </div>

    <div class="col-4 footer-contact-div" onmouseover="contactOver()" onmouseout="contactOut()" onclick="contactClick()">
        <div class="footer-contact">
            <div>
                <a asp-controller="Main" asp-action="Contact" class="footer-contact-link"><img class="footer-contact-img" src="/data/contact.png" alt="" /></a>
            </div>
        </div>
    </div>

</div>

<script type="text/javascript">

    function facebookOver() {
        var media = window.matchMedia('(hover: hover)');
        if (media.matches) {
            document.getElementsByClassName("footer-social-facebook")[0].src = "/data/facebook_color.png";
            document.body.style.cursor = "pointer";
        }
    }

    function facebookOut() {
        document.getElementsByClassName("footer-social-facebook")[0].src = "/data/facebook_footer.png";
        document.body.style.cursor = "default";
    }

    function instagramOver() {
        var media = window.matchMedia('(hover: hover)');
        if (media.matches) {
            document.getElementsByClassName("footer-social-instagram")[0].src = "/data/instagram_color.png";
            document.body.style.cursor = "pointer";
        }
    }

    function instagramOut() {
        document.getElementsByClassName("footer-social-instagram")[0].src = "/data/instagram_footer.png";
        document.body.style.cursor = "default";
    }

    function telegramOver() {
        var media = window.matchMedia('(hover: hover)');
        if (media.matches) {
            document.getElementsByClassName("footer-social-telegram")[0].src = "/data/telegram_color.png";
            document.body.style.cursor = "pointer";
        }
    }

    function telegramOut() {
        document.getElementsByClassName("footer-social-telegram")[0].src = "/data/telegram_footer.png";
        document.body.style.cursor = "default";
    }

    function contactClick() {
        document.getElementsByClassName("footer-contact-link")[0].click();
    }

    function contactOver() {
        var media = window.matchMedia('(hover: hover)');
        if (media.matches) {
            document.getElementsByClassName("footer-contact-img")[0].src = "/data/contact_color.png";
            document.body.style.cursor = "pointer";
        }
    }

    function contactOut() {
        document.getElementsByClassName("footer-contact-img")[0].src = "/data/contact.png";
        document.body.style.cursor = "default";
    }

</script>

MyLoveAgency/Views/Shared/MetatagsPartial.cshtml
<title>Lovely Love Agency</title>

<link rel="apple-touch-icon" sizes="180x180" href="/data/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/data/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/data/favicon/favicon-16x16.png">
<link rel="manifest" href="/data/favicon/site.webmanifest">

<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="description" lang="ru" content="Lovely Love Agency - это агенство, которое организовывает свидания, сюрпризы и предложения руки и сердца для влюбленных пар" />
<meta name="description" lang="en" content="A Lovely Love Agency is an agency that organizes dates, surprises and marriage proposals for couples in love" />
<meta name="description" lang="uk" content="Lovely Love Agency - це агентство, яке організовує побачення, сюрпризи і пропозиції руки і серця для закоханих пар" />

<meta name="keywords" lang="ru" content="организация свиданий, организация свиданий в Кракове, организовать сюрприз девушке, сделать сюрприз девушке, свидание в Кракове, любовные свидания, любовные свидания в Кракове, любовные сюрпризы, любовные сюрпризы в Кракове, любовные подарки"/>
<meta name="keywords" lang="en" content="organization of dates, organization of dates in Krakow, organize a surprise for a girl, make a surprise for a girl, date in Krakow, love dates, love dates in Krakow, love surprises, love surprises in Krakow, love gifts" />
<meta name="keywords" lang="uk" content="організація побачень, організація побачень в Кракові, організувати сюрприз дівчині, зробити сюрприз дівчині, побачення в Кракові, любовні побачення, любовні побачення в Кракові, любовні сюрпризи, любовні сюрпризи в Кракові, любовні подарунки" />

<script>history.scrollRestoration = "manual"</script>

MyLoveAgency/Views/Shared/ScriptsPartial.cshtml
<script src="~/js/bootstrap.bundle.min.js" asp-append-version="true"></script>

MyLoveAgency/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @await Html.PartialAsync("MetatagsPartial")
    @await Html.PartialAsync("CssPartial")
</head>
<body>
    @await Html.PartialAsync("HeaderPartial")

    @RenderBody()

    @await Html.PartialAsync("FooterPartial")
    @await Html.PartialAsync("ScriptsPartial")
</body>
</html>